version: '3.8'

services:
  library-management-system:
    image: edsonwade126/library-management-system:latest
    container_name: library-management
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/library_management_db
      POSTGRES_USERNAME: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: '8080'
      HIBERNATE_DDL_AUTO: 'update'
      SPRING_PROFILES_ACTIVE: 'docker'
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: library_management_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./src/main/resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - prometheus_data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - library-management-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always
    networks:
      - library-management-net
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin

volumes:
  postgres_data:
    driver: local  # Volume for PostgreSQL persistence
  prometheus_data:
    driver: local  # Volume for PostgreSQL persistence
  grafana_data:
    driver: local  # Volume for PostgreSQL persistence

networks:
  library-management-net:
    driver: bridge
