server:
  port: 8081

spring:
  application:
    name: library-management-system
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      format_sql: true
      show-sql: true
    database:
      platform: h2
    open-in-view: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /library-api.html
    operationsSorter: method
    tagsSorter: alpha
    default-sort: method,asc