server:
  port: 8081

spring:
  application:
    name: library-management-system
  datasource:
    url: jdbc:postgresql://localhost:5432/library_management_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    database-platform: postgresql
    open-in-view: true
    show-sql: true
    format-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  appoptics:
    metrics:
      export:
        api-token:
  datadog:
    metrics:
      export:
        api-key:
  dynatrace:
    metrics:
      export:
        api-token:

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /library-api.html
    operationsSorter: method
    tagsSorter: alpha
    default-sort: method,asc


api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}   # default to my-secret-key if not found


  flyway:
    locations: classpath:db/migration/  # Ensure your migrations are here
    baseline-on-migrate: true           # Baseline the database if necessary
    baseline-version: 1                 # The version to baseline from
    enabled: true
    baseline-description: "init"
    out-of-order: true                  # Allow applying migrations out of order
    ignore-migration-patterns: "*:ignored"  # Ignore migrations with this pattern


